export const cities = [
  { id: 1, name: "New York", stores: 12, products: 342, understock: 8, overstock: 3, value: 187420 },
  { id: 2, name: "Los Angeles", stores: 10, products: 289, understock: 5, overstock: 2, value: 156890 },
  { id: 3, name: "Chicago", stores: 8, products: 245, understock: 4, overstock: 3, value: 142350 },
  { id: 4, name: "Houston", stores: 7, products: 198, understock: 3, overstock: 1, value: 98760 },
  { id: 5, name: "Phoenix", stores: 6, products: 167, understock: 2, overstock: 2, value: 89450 },
  { id: 6, name: "Philadelphia", stores: 5, products: 156, understock: 4, overstock: 1, value: 76890 },
  { id: 7, name: "San Antonio", stores: 4, products: 134, understock: 3, overstock: 0, value: 65780 },
  { id: 8, name: "San Diego", stores: 5, products: 145, understock: 2, overstock: 1, value: 71230 },
  { id: 9, name: "Dallas", stores: 6, products: 178, understock: 3, overstock: 2, value: 88940 },
  { id: 10, name: "San Jose", stores: 4, products: 123, understock: 1, overstock: 1, value: 62450 },
  { id: 11, name: "Austin", stores: 5, products: 156, understock: 2, overstock: 2, value: 78920 },
  { id: 12, name: "Jacksonville", stores: 3, products: 98, understock: 1, overstock: 0, value: 48750 },
  { id: 13, name: "Fort Worth", stores: 3, products: 87, understock: 2, overstock: 1, value: 43290 },
  { id: 14, name: "Columbus", stores: 4, products: 112, understock: 1, overstock: 0, value: 56780 },
  { id: 15, name: "Charlotte", stores: 4, products: 134, understock: 2, overstock: 1, value: 67340 },
]

export const stores = [
  {
    id: 1,
    name: "Manhattan Central",
    city: "New York",
    address: "123 Broadway Ave",
    products: 87,
    manager: "John Smith",
    phone: "(212) 555-0100",
  },
  {
    id: 2,
    name: "Downtown LA",
    city: "Los Angeles",
    address: "456 Sunset Blvd",
    products: 76,
    manager: "Sarah Johnson",
    phone: "(310) 555-0200",
  },
  {
    id: 3,
    name: "Chicago Loop",
    city: "Chicago",
    address: "789 Michigan Ave",
    products: 92,
    manager: "Mike Davis",
    phone: "(312) 555-0300",
  },
  {
    id: 4,
    name: "Houston Center",
    city: "Houston",
    address: "321 Main St",
    products: 68,
    manager: "Lisa Anderson",
    phone: "(713) 555-0400",
  },
  {
    id: 5,
    name: "Phoenix Plaza",
    city: "Phoenix",
    address: "654 Central Ave",
    products: 54,
    manager: "Tom Wilson",
    phone: "(602) 555-0500",
  },
  {
    id: 6,
    name: "Philly Market",
    city: "Philadelphia",
    address: "987 Market St",
    products: 61,
    manager: "Emma Brown",
    phone: "(215) 555-0600",
  },
  {
    id: 7,
    name: "San Antonio Mall",
    city: "San Antonio",
    address: "147 Commerce St",
    products: 48,
    manager: "David Lee",
    phone: "(210) 555-0700",
  },
  {
    id: 8,
    name: "San Diego Bay",
    city: "San Diego",
    address: "258 Harbor Dr",
    products: 52,
    manager: "Jennifer White",
    phone: "(619) 555-0800",
  },
  {
    id: 9,
    name: "Dallas Marketplace",
    city: "Dallas",
    address: "369 Elm St",
    products: 71,
    manager: "Chris Martin",
    phone: "(214) 555-0900",
  },
]

export const products = [
  // Understock items (13 total)
  {
    id: 1,
    name: "Wireless Mouse",
    sku: "WM-001",
    stock: 8,
    minStock: 20,
    maxStock: 100,
    price: 29.99,
    city: "New York",
    category: "Electronics",
  },
  {
    id: 2,
    name: "USB-C Cable",
    sku: "UC-002",
    stock: 12,
    minStock: 30,
    maxStock: 150,
    price: 12.99,
    city: "Los Angeles",
    category: "Accessories",
  },
  {
    id: 3,
    name: "Keyboard Mechanical",
    sku: "KB-003",
    stock: 5,
    minStock: 15,
    maxStock: 60,
    price: 89.99,
    city: "Chicago",
    category: "Electronics",
  },
  {
    id: 4,
    name: "Headphones Wireless",
    sku: "HP-004",
    stock: 7,
    minStock: 25,
    maxStock: 100,
    price: 149.99,
    city: "Houston",
    category: "Audio",
  },
  {
    id: 5,
    name: "HDMI Cable 6ft",
    sku: "HD-005",
    stock: 14,
    minStock: 40,
    maxStock: 200,
    price: 15.99,
    city: "Phoenix",
    category: "Cables",
  },
  {
    id: 6,
    name: "Phone Charger",
    sku: "PC-006",
    stock: 18,
    minStock: 50,
    maxStack: 250,
    price: 19.99,
    city: "Philadelphia",
    category: "Accessories",
  },
  {
    id: 7,
    name: "Laptop Bag",
    sku: "LB-007",
    stock: 9,
    minStock: 20,
    maxStock: 80,
    price: 45.99,
    city: "San Antonio",
    category: "Accessories",
  },
  {
    id: 8,
    name: "External SSD 1TB",
    sku: "ES-008",
    stock: 6,
    minStock: 15,
    maxStock: 50,
    price: 129.99,
    city: "San Diego",
    category: "Storage",
  },
  {
    id: 9,
    name: "Webcam 1080p",
    sku: "WC-009",
    stock: 11,
    minStock: 25,
    maxStock: 75,
    price: 79.99,
    city: "Dallas",
    category: "Electronics",
  },
  {
    id: 10,
    name: "USB Hub 7-Port",
    sku: "UH-010",
    stock: 13,
    minStock: 30,
    maxStock: 100,
    price: 34.99,
    city: "San Jose",
    category: "Accessories",
  },
  {
    id: 11,
    name: "Screen Protector",
    sku: "SP-011",
    stock: 22,
    minStock: 60,
    maxStock: 300,
    price: 9.99,
    city: "Austin",
    category: "Accessories",
  },
  {
    id: 12,
    name: "Bluetooth Speaker",
    sku: "BS-012",
    stock: 8,
    minStock: 20,
    maxStock: 80,
    price: 59.99,
    city: "Jacksonville",
    category: "Audio",
  },
  {
    id: 13,
    name: "Gaming Mouse Pad",
    sku: "GM-013",
    stock: 16,
    minStock: 40,
    maxStock: 150,
    price: 24.99,
    city: "Fort Worth",
    category: "Accessories",
  },

  // Overstock items (10 total)
  {
    id: 14,
    name: "Laptop Stand",
    sku: "LS-014",
    stock: 156,
    minStock: 25,
    maxStock: 80,
    price: 49.99,
    city: "Chicago",
    category: "Accessories",
  },
  {
    id: 15,
    name: "Mouse Pad Basic",
    sku: "MP-015",
    stock: 203,
    minStock: 50,
    maxStock: 150,
    price: 19.99,
    city: "New York",
    category: "Accessories",
  },
  {
    id: 16,
    name: "Cable Organizer",
    sku: "CO-016",
    stock: 178,
    minStock: 40,
    maxStock: 120,
    price: 14.99,
    city: "Los Angeles",
    category: "Accessories",
  },
  {
    id: 17,
    name: "Phone Stand",
    sku: "PS-017",
    stock: 145,
    minStock: 30,
    maxStock: 100,
    price: 22.99,
    city: "Houston",
    category: "Accessories",
  },
  {
    id: 18,
    name: "Stylus Pen",
    sku: "ST-018",
    stock: 167,
    minStock: 35,
    maxStock: 110,
    price: 29.99,
    city: "Phoenix",
    category: "Accessories",
  },
  {
    id: 19,
    name: 'Laptop Sleeve 15"',
    sku: "LV-019",
    stock: 134,
    minStock: 25,
    maxStock: 90,
    price: 32.99,
    city: "Philadelphia",
    category: "Accessories",
  },
  {
    id: 20,
    name: "Desk Lamp LED",
    sku: "DL-020",
    stock: 121,
    minStock: 20,
    maxStock: 70,
    price: 39.99,
    city: "San Antonio",
    category: "Lighting",
  },
  {
    id: 21,
    name: "Microfiber Cloths",
    sku: "MC-021",
    stock: 245,
    minStock: 100,
    maxStock: 200,
    price: 12.99,
    city: "San Diego",
    category: "Cleaning",
  },
  {
    id: 22,
    name: "Cable Ties Pack",
    sku: "CT-022",
    stock: 298,
    minStock: 80,
    maxStock: 180,
    price: 8.99,
    city: "Dallas",
    category: "Accessories",
  },
  {
    id: 23,
    name: "Sticky Notes Set",
    sku: "SN-023",
    stock: 187,
    minStock: 60,
    maxStock: 140,
    price: 11.99,
    city: "San Jose",
    category: "Office",
  },

  // Optimal stock items (77 total to reach 100)
  {
    id: 24,
    name: 'Monitor 27"',
    sku: "MN-024",
    stock: 34,
    minStock: 10,
    maxStock: 40,
    price: 299.99,
    city: "Austin",
    category: "Electronics",
  },
  {
    id: 25,
    name: "Ergonomic Mouse",
    sku: "EM-025",
    stock: 45,
    minStock: 20,
    maxStock: 80,
    price: 39.99,
    city: "Charlotte",
    category: "Electronics",
  },
  {
    id: 26,
    name: "Wireless Keyboard",
    sku: "WK-026",
    stock: 52,
    minStock: 25,
    maxStock: 100,
    price: 69.99,
    city: "Columbus",
    category: "Electronics",
  },
  {
    id: 27,
    name: "USB Drive 64GB",
    sku: "UD-027",
    stock: 78,
    minStock: 40,
    maxStock: 150,
    price: 18.99,
    city: "New York",
    category: "Storage",
  },
  {
    id: 28,
    name: "Ethernet Cable 10ft",
    sku: "EC-028",
    stock: 91,
    minStock: 50,
    maxStock: 200,
    price: 13.99,
    city: "Los Angeles",
    category: "Cables",
  },
  {
    id: 29,
    name: "Printer Paper Ream",
    sku: "PP-029",
    stock: 67,
    minStock: 30,
    maxStock: 120,
    price: 24.99,
    city: "Chicago",
    category: "Office",
  },
  {
    id: 30,
    name: "Wireless Charger",
    sku: "WC-030",
    stock: 43,
    minStock: 20,
    maxStock: 75,
    price: 32.99,
    city: "Houston",
    category: "Accessories",
  },
  {
    id: 31,
    name: "Graphics Tablet",
    sku: "GT-031",
    stock: 28,
    minStock: 10,
    maxStock: 50,
    price: 159.99,
    city: "Phoenix",
    category: "Electronics",
  },
  {
    id: 32,
    name: "USB-C Hub",
    sku: "UH-032",
    stock: 56,
    minStock: 25,
    maxStock: 90,
    price: 44.99,
    city: "Philadelphia",
    category: "Accessories",
  },
  {
    id: 33,
    name: "Laptop Cooler",
    sku: "LC-033",
    stock: 38,
    minStock: 15,
    maxStock: 60,
    price: 34.99,
    city: "San Antonio",
    category: "Accessories",
  },
  {
    id: 34,
    name: "Smartphone Gimbal",
    sku: "SG-034",
    stock: 22,
    minStock: 8,
    maxStock: 35,
    price: 129.99,
    city: "San Diego",
    category: "Electronics",
  },
  {
    id: 35,
    name: "Ring Light",
    sku: "RL-035",
    stock: 31,
    minStock: 12,
    maxStock: 45,
    price: 54.99,
    city: "Dallas",
    category: "Lighting",
  },
  {
    id: 36,
    name: "Microphone USB",
    sku: "MU-036",
    stock: 26,
    minStock: 10,
    maxStock: 40,
    price: 89.99,
    city: "San Jose",
    category: "Audio",
  },
  {
    id: 37,
    name: "Drawing Tablet",
    sku: "DT-037",
    stock: 19,
    minStock: 8,
    maxStock: 30,
    price: 249.99,
    city: "Austin",
    category: "Electronics",
  },
  {
    id: 38,
    name: "Surge Protector",
    sku: "SP-038",
    stock: 74,
    minStock: 35,
    maxStock: 120,
    price: 27.99,
    city: "Charlotte",
    category: "Accessories",
  },
  {
    id: 39,
    name: "Monitor Mount",
    sku: "MM-039",
    stock: 33,
    minStock: 15,
    maxStock: 55,
    price: 79.99,
    city: "Columbus",
    category: "Accessories",
  },
  {
    id: 40,
    name: "Docking Station",
    sku: "DS-040",
    stock: 24,
    minStock: 10,
    maxStock: 40,
    price: 199.99,
    city: "New York",
    category: "Electronics",
  },
  {
    id: 41,
    name: "Webcam Cover",
    sku: "WV-041",
    stock: 112,
    minStock: 60,
    maxStock: 180,
    price: 6.99,
    city: "Los Angeles",
    category: "Accessories",
  },
  {
    id: 42,
    name: "Bluetooth Adapter",
    sku: "BA-042",
    stock: 68,
    minStock: 30,
    maxStock: 100,
    price: 16.99,
    city: "Chicago",
    category: "Accessories",
  },
  {
    id: 43,
    name: "Memory Card 128GB",
    sku: "MC-043",
    stock: 55,
    minStock: 25,
    maxStock: 90,
    price: 22.99,
    city: "Houston",
    category: "Storage",
  },
  {
    id: 44,
    name: "Card Reader",
    sku: "CR-044",
    stock: 47,
    minStock: 20,
    maxStock: 75,
    price: 14.99,
    city: "Phoenix",
    category: "Accessories",
  },
  {
    id: 45,
    name: "Portable SSD 2TB",
    sku: "PS-045",
    stock: 18,
    minStock: 8,
    maxStock: 30,
    price: 189.99,
    city: "Philadelphia",
    category: "Storage",
  },
  {
    id: 46,
    name: "NAS 4-Bay",
    sku: "NB-046",
    stock: 12,
    minStock: 5,
    maxStock: 20,
    price: 399.99,
    city: "San Antonio",
    category: "Storage",
  },
  {
    id: 47,
    name: "KVM Switch",
    sku: "KS-047",
    stock: 29,
    minStock: 12,
    maxStock: 45,
    price: 54.99,
    city: "San Diego",
    category: "Electronics",
  },
  {
    id: 48,
    name: "Audio Interface",
    sku: "AI-048",
    stock: 16,
    minStock: 7,
    maxStock: 25,
    price: 149.99,
    city: "Dallas",
    category: "Audio",
  },
  {
    id: 49,
    name: "Studio Monitors",
    sku: "SM-049",
    stock: 14,
    minStock: 6,
    maxStock: 22,
    price: 279.99,
    city: "San Jose",
    category: "Audio",
  },
  {
    id: 50,
    name: "MIDI Keyboard",
    sku: "MK-050",
    stock: 21,
    minStock: 8,
    maxStock: 32,
    price: 119.99,
    city: "Austin",
    category: "Audio",
  },
  {
    id: 51,
    name: "Pop Filter",
    sku: "PF-051",
    stock: 63,
    minStock: 30,
    maxStock: 100,
    price: 12.99,
    city: "Charlotte",
    category: "Audio",
  },
  {
    id: 52,
    name: "Boom Arm",
    sku: "BA-052",
    stock: 37,
    minStock: 15,
    maxStock: 55,
    price: 39.99,
    city: "Columbus",
    category: "Audio",
  },
  {
    id: 53,
    name: "Acoustic Foam",
    sku: "AF-053",
    stock: 48,
    minStock: 20,
    maxStock: 75,
    price: 29.99,
    city: "New York",
    category: "Audio",
  },
  {
    id: 54,
    name: "Camera Tripod",
    sku: "CT-054",
    stock: 42,
    minStock: 18,
    maxStock: 65,
    price: 44.99,
    city: "Los Angeles",
    category: "Photography",
  },
  {
    id: 55,
    name: "Lens Cleaning Kit",
    sku: "LK-055",
    stock: 71,
    minStock: 35,
    maxStock: 110,
    price: 14.99,
    city: "Chicago",
    category: "Photography",
  },
  {
    id: 56,
    name: "Camera Bag",
    sku: "CB-056",
    stock: 34,
    minStock: 15,
    maxStock: 50,
    price: 59.99,
    city: "Houston",
    category: "Photography",
  },
  {
    id: 57,
    name: "Flash Speedlight",
    sku: "FS-057",
    stock: 23,
    minStock: 10,
    maxStock: 35,
    price: 89.99,
    city: "Phoenix",
    category: "Photography",
  },
  {
    id: 58,
    name: "Green Screen",
    sku: "GS-058",
    stock: 27,
    minStock: 12,
    maxStock: 40,
    price: 49.99,
    city: "Philadelphia",
    category: "Photography",
  },
  {
    id: 59,
    name: "Softbox Light Kit",
    sku: "SL-059",
    stock: 19,
    minStock: 8,
    maxStock: 30,
    price: 99.99,
    city: "San Antonio",
    category: "Lighting",
  },
  {
    id: 60,
    name: "Light Stand",
    sku: "LS-060",
    stock: 44,
    minStock: 20,
    maxStock: 70,
    price: 34.99,
    city: "San Diego",
    category: "Lighting",
  },
  {
    id: 61,
    name: "Reflector 5-in-1",
    sku: "RF-061",
    stock: 36,
    minStock: 15,
    maxStock: 55,
    price: 24.99,
    city: "Dallas",
    category: "Photography",
  },
  {
    id: 62,
    name: "Monitor Calibrator",
    sku: "MC-062",
    stock: 17,
    minStock: 7,
    maxStock: 25,
    price: 169.99,
    city: "San Jose",
    category: "Electronics",
  },
  {
    id: 63,
    name: "Graphics Card",
    sku: "GC-063",
    stock: 15,
    minStock: 6,
    maxStock: 22,
    price: 599.99,
    city: "Austin",
    category: "Electronics",
  },
  {
    id: 64,
    name: "RAM 32GB Kit",
    sku: "RM-064",
    stock: 28,
    minStock: 12,
    maxStock: 45,
    price: 119.99,
    city: "Charlotte",
    category: "Electronics",
  },
  {
    id: 65,
    name: "CPU Cooler",
    sku: "CC-065",
    stock: 32,
    minStock: 14,
    maxStock: 50,
    price: 79.99,
    city: "Columbus",
    category: "Electronics",
  },
  {
    id: 66,
    name: "Motherboard ATX",
    sku: "MB-066",
    stock: 11,
    minStock: 5,
    maxStock: 18,
    price: 249.99,
    city: "New York",
    category: "Electronics",
  },
  {
    id: 67,
    name: "Power Supply 750W",
    sku: "PS-067",
    stock: 24,
    minStock: 10,
    maxStock: 35,
    price: 129.99,
    city: "Los Angeles",
    category: "Electronics",
  },
  {
    id: 68,
    name: "PC Case",
    sku: "PC-068",
    stock: 16,
    minStock: 7,
    maxStock: 25,
    price: 89.99,
    city: "Chicago",
    category: "Electronics",
  },
  {
    id: 69,
    name: "Thermal Paste",
    sku: "TP-069",
    stock: 94,
    minStock: 50,
    maxStock: 150,
    price: 8.99,
    city: "Houston",
    category: "Accessories",
  },
  {
    id: 70,
    name: "Cable Sleeves",
    sku: "CS-070",
    stock: 76,
    minStock: 40,
    maxStock: 120,
    price: 19.99,
    city: "Phoenix",
    category: "Accessories",
  },
  {
    id: 71,
    name: "Fan Controller",
    sku: "FC-071",
    stock: 38,
    minStock: 16,
    maxStock: 60,
    price: 34.99,
    city: "Philadelphia",
    category: "Electronics",
  },
  {
    id: 72,
    name: "RGB LED Strip",
    sku: "RL-072",
    stock: 82,
    minStock: 40,
    maxStock: 130,
    price: 24.99,
    city: "San Antonio",
    category: "Lighting",
  },
  {
    id: 73,
    name: "Smart Plug",
    sku: "SP-073",
    stock: 67,
    minStock: 30,
    maxStock: 100,
    price: 19.99,
    city: "San Diego",
    category: "Electronics",
  },
  {
    id: 74,
    name: "Smart Light Bulb",
    sku: "SL-074",
    stock: 89,
    minStock: 45,
    maxStock: 140,
    price: 14.99,
    city: "Dallas",
    category: "Lighting",
  },
  {
    id: 75,
    name: "Security Camera",
    sku: "SC-075",
    stock: 31,
    minStock: 14,
    maxStock: 50,
    price: 79.99,
    city: "San Jose",
    category: "Electronics",
  },
  {
    id: 76,
    name: "Door Sensor",
    sku: "DS-076",
    stock: 54,
    minStock: 25,
    maxStock: 85,
    price: 24.99,
    city: "Austin",
    category: "Electronics",
  },
  {
    id: 77,
    name: "Motion Detector",
    sku: "MD-077",
    stock: 46,
    minStock: 20,
    maxStock: 70,
    price: 29.99,
    city: "Charlotte",
    category: "Electronics",
  },
  {
    id: 78,
    name: "Smart Thermostat",
    sku: "ST-078",
    stock: 23,
    minStock: 10,
    maxStock: 35,
    price: 149.99,
    city: "Columbus",
    category: "Electronics",
  },
  {
    id: 79,
    name: "Smart Lock",
    sku: "SL-079",
    stock: 18,
    minStock: 8,
    maxStock: 28,
    price: 199.99,
    city: "New York",
    category: "Electronics",
  },
  {
    id: 80,
    name: "Video Doorbell",
    sku: "VD-080",
    stock: 26,
    minStock: 11,
    maxStock: 40,
    price: 169.99,
    city: "Los Angeles",
    category: "Electronics",
  },
  {
    id: 81,
    name: "Network Switch",
    sku: "NS-081",
    stock: 35,
    minStock: 15,
    maxStock: 55,
    price: 79.99,
    city: "Chicago",
    category: "Electronics",
  },
  {
    id: 82,
    name: "WiFi Router",
    sku: "WR-082",
    stock: 41,
    minStock: 18,
    maxStock: 65,
    price: 119.99,
    city: "Houston",
    category: "Electronics",
  },
  {
    id: 83,
    name: "Mesh WiFi System",
    sku: "MW-083",
    stock: 22,
    minStock: 9,
    maxStock: 33,
    price: 249.99,
    city: "Phoenix",
    category: "Electronics",
  },
  {
    id: 84,
    name: "Range Extender",
    sku: "RE-084",
    stock: 58,
    minStock: 25,
    maxStock: 90,
    price: 44.99,
    city: "Philadelphia",
    category: "Electronics",
  },
  {
    id: 85,
    name: "Modem Cable",
    sku: "MC-085",
    stock: 73,
    minStock: 35,
    maxStock: 115,
    price: 16.99,
    city: "San Antonio",
    category: "Cables",
  },
  {
    id: 86,
    name: "Powerline Adapter",
    sku: "PA-086",
    stock: 39,
    minStock: 17,
    maxStock: 60,
    price: 54.99,
    city: "San Diego",
    category: "Electronics",
  },
  {
    id: 87,
    name: "UPS Battery Backup",
    sku: "UB-087",
    stock: 27,
    minStock: 11,
    maxStock: 42,
    price: 139.99,
    city: "Dallas",
    category: "Electronics",
  },
  {
    id: 88,
    name: "Cable Tester",
    sku: "CT-088",
    stock: 33,
    minStock: 14,
    maxStock: 50,
    price: 29.99,
    city: "San Jose",
    category: "Tools",
  },
  {
    id: 89,
    name: "Crimping Tool",
    sku: "CT-089",
    stock: 41,
    minStock: 18,
    maxStock: 65,
    price: 34.99,
    city: "Austin",
    category: "Tools",
  },
  {
    id: 90,
    name: "Screwdriver Set",
    sku: "SS-090",
    stock: 64,
    minStock: 30,
    maxStock: 100,
    price: 24.99,
    city: "Charlotte",
    category: "Tools",
  },
  {
    id: 91,
    name: "Anti-Static Wrist Strap",
    sku: "AW-091",
    stock: 87,
    minStock: 45,
    maxStock: 135,
    price: 9.99,
    city: "Columbus",
    category: "Tools",
  },
  {
    id: 92,
    name: "Multimeter",
    sku: "MT-092",
    stock: 36,
    minStock: 15,
    maxStock: 55,
    price: 39.99,
    city: "New York",
    category: "Tools",
  },
  {
    id: 93,
    name: "Soldering Iron",
    sku: "SI-093",
    stock: 29,
    minStock: 12,
    maxStock: 45,
    price: 44.99,
    city: "Los Angeles",
    category: "Tools",
  },
  {
    id: 94,
    name: "Heat Gun",
    sku: "HG-094",
    stock: 21,
    minStock: 9,
    maxStock: 32,
    price: 54.99,
    city: "Chicago",
    category: "Tools",
  },
  {
    id: 95,
    name: "Wire Stripper",
    sku: "WS-095",
    stock: 52,
    minStock: 23,
    maxStock: 80,
    price: 19.99,
    city: "Houston",
    category: "Tools",
  },
  {
    id: 96,
    name: "Precision Tweezers",
    sku: "PT-096",
    stock: 69,
    minStock: 32,
    maxStock: 105,
    price: 12.99,
    city: "Phoenix",
    category: "Tools",
  },
  {
    id: 97,
    name: "Tool Kit 115-Piece",
    sku: "TK-097",
    stock: 34,
    minStock: 14,
    maxStock: 52,
    price: 89.99,
    city: "Philadelphia",
    category: "Tools",
  },
  {
    id: 98,
    name: "Compressed Air Can",
    sku: "CA-098",
    stock: 98,
    minStock: 50,
    maxStock: 155,
    price: 11.99,
    city: "San Antonio",
    category: "Cleaning",
  },
  {
    id: 99,
    name: "Cleaning Gel",
    sku: "CG-099",
    stock: 76,
    minStock: 38,
    maxStock: 118,
    price: 8.99,
    city: "San Diego",
    category: "Cleaning",
  },
  {
    id: 100,
    name: "Screen Cleaner Spray",
    sku: "SC-100",
    stock: 81,
    minStock: 42,
    maxStock: 127,
    price: 9.99,
    city: "Dallas",
    category: "Cleaning",
  },
]

export const generateLiveAlerts = (count: number) => {
  const alerts = []
  const statuses = ["Stock OK", "Low Stock", "Overstock"]
  const forecasts = ["N/A", "Reorder Soon", "Stable", "Monitor"]

  for (let i = 0; i < count; i++) {
    const product = products[Math.floor(Math.random() * products.length)]
    const status =
      product.stock < product.minStock ? "Low Stock" : product.stock > product.maxStock ? "Overstock" : "Stock OK"
    const currentTime = new Date()
    currentTime.setSeconds(currentTime.getSeconds() - i * 16)

    alerts.push({
      id: i + 1,
      time: currentTime.toLocaleTimeString("en-US", { hour12: false }),
      city: product.city,
      store: stores[Math.floor(Math.random() * stores.length)].name,
      product: product.name,
      sale: -Math.floor(Math.random() * 10) - 1,
      stock: product.stock,
      status: status,
      forecast: status === "Low Stock" ? "Reorder Soon" : "N/A",
    })
  }

  return alerts
}

export const mockProducts = products
